[project]
name = "myproject"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "SamarSaeed1146", email = "samarsaeed@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "litellm>=1.59.1",
]

[project.scripts]
gemini = "myproject:hello.gemini"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
